#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Setup python env from generated file (generated by tools/repoman/build.py)
export CARB_APP_PATH="$SCRIPT_DIR/kit"
export ISAAC_PATH="$SCRIPT_DIR"
export EXP_PATH="$SCRIPT_DIR/apps"
source $SCRIPT_DIR/setup_python_env.sh

python_exe="$SCRIPT_DIR/kit/python/bin/python3"

# Show icon if not running headless
export RESOURCE_NAME="IsaacSim"
# WAR for missing libcarb.so
export LD_PRELOAD="$SCRIPT_DIR/kit/libcarb.so"

$python_exe "$@" || error_exit
